version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - ./:/projectMongo
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=order-service
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=root
    volumes:
      - ./:/projectMysql
    ports:
      - "3306:3306"



#  web-server:
#    container_name: web-server
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
#    environment:
#      - SERVER_PORT= 8080
#      - TZ=Europe/Moscow
#      - LOG_MODE=dev