version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - ./:/project
    ports:
      - "27017:27017"

  web-server:
    container_name: web-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SERVER_PORT= 8080
      - TZ=Europe/Moscow
      - LOG_MODE=dev